### ISSUE TITLE
Add AV1 support

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-streamer#10]
We don't yet support AV1, but this should be easy to add.

**Comment by joeyparrish** [comment]
AV1 support appears more complicated than I realized.  I'm having issues getting it to work in Shaka Packager v2.3.0.  @kqyang, is AV1 already supported in Packager?

**Comment by kqyang** [comment]
@joeyparrish Yes, AV1 is already supported, though we did not implement all features. What is the issue you are encountering?

**Comment by joeyparrish** [comment]
I've narrowed it down to two issues:

1. FFmpeg throws an error if I write AV1-in-WebM to a pipe (but it's fine writing to a file).
2. Shaka Packager hangs reading any codec in MP4 from a pipe

So I think my issue may not be specific to AV1.
