### ISSUE TITLE
Help debugging python transcoding / streaming server

### ISSUE THREAD

**Issue by inglesuniversal** [google/shaka-streamer#100]
After installing the scripts and libraries on my MacBook Air ... I was able to upload the transcoded MOV file into one of my AWS buckets.... I left ALL the settings in the pipeline_vod_file.yaml UNTOUCHED.

The video plays beautifully on your Player or pasting the URL on my desktop copy of VLC

BUT... 

NO audio comes out in the output files once stored on my bucket, during playback the speaker icon remains disabled all the way through.

Any IDEAS on how to enable the audio / codec properly?

Regards

Hugo Barbosa

PS: Amazing Project!!!

**Comment by inglesuniversal** [comment]
Thanks for the prompt reply...

    $    ffprobe -i SAMPLE_FILE.mov 
    ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
    built with Apple clang version 12.0.5 (clang-1205.0.22.9)
    configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang -- 
    host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable- 
    libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable- 
    libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp -- 
    enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable- 
    libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable- 
    libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack -- 
    enable-avresample --enable-videotoolbox
    libavutil      56. 70.100 / 56. 70.100
    libavcodec     58.134.100 / 58.134.100
    libavformat    58. 76.100 / 58. 76.100
    libavdevice    58. 13.100 / 58. 13.100
    libavfilter     7.110.100 /  7.110.100
    libavresample   4.  0.  0 /  4.  0.  0
    libswscale      5.  9.100 /  5.  9.100
    libswresample   3.  9.100 /  3.  9.100
    libpostproc    55.  9.100 / 55.  9.100
    Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Papa_y_Sunny_Teleferico.mov':
    Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2021-04-16T18:09:14.000000Z
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 11
    com.apple.quicktime.software: 14.4.2
    com.apple.quicktime.creationdate: 2021-04-16T13:09:14-0500
    Duration: 00:00:16.37, start: 0.000000, bitrate: 8035 kb/s
    Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, 7739 kb/s, 30 fps, 30 tbr, 600 
    tbn, 600 tbc (default)
    Metadata:
      rotate          : 180
      creation_time   : 2021-04-16T18:09:14.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : HEVC
    Side data:
      displaymatrix: rotation of -180.00 degrees
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 188 kb/s (default)
      Metadata:
      creation_time   : 2021-04-16T18:09:14.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
    Stream #0:2(und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2021-04-16T18:09:14.000000Z
      handler_name    : Core Media Metadata
    Stream #0:3(und): Data: none (mebx / 0x7862656D), 39 kb/s (default)
    Metadata:
      creation_time   : 2021-04-16T18:09:14.000000Z
      handler_name    : Core Media Metadata
    Stream #0:4(und): Data: none (mebx / 0x7862656D), 47 kb/s (default)
    Metadata:
      creation_time   : 2021-04-16T18:09:14.000000Z
      handler_name    : Core Media Metadata
      Unsupported codec with id 0 for input stream 2
      Unsupported codec with id 0 for input stream 3
      Unsupported codec with id 0 for input stream 4

**Comment by inglesuniversal** [comment]
YAML FILES follow...
[Archive.zip](https://github.com/google/shaka-streamer/files/7306298/Archive.zip)
.

**Comment by joeyparrish** [comment]
> Now... what would be the steps to mount this on a python3 web server having curl / php / node.js in order to call this function once the files (MOV) are uploaded.

You can use the Python module API instead of the command-line in your Python-based web server, and there's a great example of this in our test runner.  Check out `run_end_to_end_tests.py`, which uses Flask to run a web server and trigger Streamer encodes based on web requests.  Our tests (written in JavaScript, running in a browser) will send a request to the local test server to start an encoder, then start streaming the content from the local server to test that it is playable (using Shaka Player in the browser).

> Can this script work with remote URLs or the files have to be in the same folder (downloaded first)?

With a new release of shaka-streamer-binaries including the fix for https://github.com/joeyparrish/static-ffmpeg-binaries/issues/2, we will be able to do that.  The n4.4-1 release of static-ffmpeg-binaries and the corresponding 0.5.0 release of shaka-streamer-binaries are missing TLS support in FFmpeg.

I'll try to get that out soon.

> NOTE: How can I extract the 1st frame as an image (.jpg or preferably .webp) ?

I suggest you use FFmpeg directly for this: https://stackoverflow.com/a/27573049

**Comment by inglesuniversal** [comment]
Ran it again with a brand new bucket at AWS ... and got this error too...

        frame=   40 fps=1.7 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 size=       0kB time=00:00:00.50 bitrate=   0.6kbits/s speed=
        Traceback (most recent call last):
        File "/opt/bitnami/apache/htdocs/shaka-streamer/google-cloud-sdk/platform/gsutil/gsutil", line 21, in <module>
        gsutil.RunMain()
        File "/opt/bitnami/apache/htdocs/shaka-streamer/google-cloud-sdk/platform/gsutil/gsutil.py", line 122, in RunMain
        sys.exit(gslib.__main__.main())
        File "/opt/bitnami/apache/htdocs/shaka-streamer/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 444, in main
        user_project=user_project)
        File "/opt/bitnami/apache/htdocs/shaka-streamer/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 782, in _RunNamedComm
        andAndHandleExceptions
        frame=   41 fps=1.6 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 size=       0kB time=00:00:00.53 bitrate=   0.5kbits/s speed=
        _HandleUnknownFailure(e)
        frame=   41 fps=1.6 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 size=       0kB time=00:00:00.53 bitrate=   0.5kbits/s speed=
        _HandleUnknownFailure(e)
        File "/opt/bitnami/apache/htdocs/shaka-streamer/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 639, in _RunNamedComm
        andAndHandleExceptions
        user_project=user_project)
        File "/opt/bitnami/apache/htdocs/shaka-streamer/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 412, in RunName
        dCommand
        return_code = command_inst.RunCommand()
        File "/opt/bitnami/apache/htdocs/shaka-streamer/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1672, in RunCom
        mand
        diff_iterator = _DiffIterator(self, src_url, dst_url)
        File "/opt/bitnami/apache/htdocs/shaka-streamer/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1003, in __init
        __
        fail_on_error=True)
        File "/opt/bitnami/apache/htdocs/shaka-streamer/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1524, in Apply
        parallel_operations_override=parallel_operations_override)
        File "/opt/bitnami/apache/htdocs/shaka-streamer/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1721, in _ParallelAppl
        y
        user_project=self.user_project)
        File "/opt/bitnami/apache/htdocs/shaka-streamer/google-cloud-sdk/platform/gsutil/gslib/command.py", line 2222, in __init__
        worker_thread.start()
        File "/usr/lib/python3.7/threading.py", line 847, in start
        _start_new_thread(self._bootstrap, ())
        RuntimeError: can't start new thread
        Exception in cloud - (<class 'subprocess.CalledProcessError'>, CalledProcessError(1, ['gsutil', '-q', '-h', 'Cache-Control: no-st
        ore, no-transform', '-m', 'rsync', '-C', '-r', '-d', '-x', '.*m3u8', '-x', '.*mpd', 'output_files', 's3://mycloudvip-shaka-stream
        er/demo/']), <traceback object at 0x7f3454b2a0c8>)
        CloudNode: 'Continuing.'

**Comment by meryacine** [comment]
Hello @inglesuniversal , Based on [this](https://stackoverflow.com/questions/1834919/error-cant-start-new-thread) and [this](https://stackoverflow.com/questions/32283003/python-cant-start-new-thread-100-active-threads) SoF threads, I think it is the system on the remote server blocking the creation of new threads due to a user limit.

**Comment by inglesuniversal** [comment]
Before I investigate any further. Are there any minimum requirements for this script to run? My Mac has 8gb or RAM while the remote VM has only 2 GB. Can codelab machines be used for this type of process?

**Comment by meryacine** [comment]
The script it self is light weight, but the ffmpeg and packager processes managed by the script may vary in resource usage based on the inputs and the pipeline used, there is no specific minimum requirement as per my knowledge, it is mostly based on how big your encoding pipeline is.
Don't know about codelab :(, a google search surprisingly didn't help.

**Comment by inglesuniversal** [comment]
Sure... I'll look into all the suggestions and ideas you and your TEAM are kindly proving me!
