### ISSUE TITLE
How to convert video chunks created by shaka streamer to a tiny video that can be played using ffmpeg?

### ISSUE THREAD

**Issue by upanitag** [google/shaka-streamer#101]
Hi,
How can I convert each webm chunk generated via shaka streamer into a proper video? I don't want to combine the chunks to one video but rather convert each tiny chunk to its own video. Is that feasible using ffmpeg and how?

For example, shaka streamer generates the following

 video_1080p_2M_vp9_init.webm
 video_1080p_2M_vp9_1.webm
video_1080p_2M_vp9_2.webm
 video_1080p_2M_vp9_3.webm
 video_1080p_2M_vp9_4.webm
 video_1080p_2M_vp9_5.webm

The chunks 1 to 5 are not playable on its own using VLC player etc. How do I convert each of them to 5 tiny playable videos?

Thanks,
Upanita

**Comment by meryacine** [comment]
I just tried what Joey said, found that you can concatenate the init segment with any other segment to create the chunk you wanted playable by it self.
```sh
cat video_1080p_2M_vp9_{init,1}.webm > video_first_chunk.webm
```
and for the sixth chunk for example:
```sh
cat video_1080p_2M_vp9_{init,6}.webm > video_sixth_chunk.webm
```
