### ISSUE TITLE
Security vulnerabilty

### ISSUE THREAD

**Issue by haby0** [google/shaka-streamer#102]
What would be the right contact to report a security vulnerabilty? thanks!

**Comment by joeyparrish** [comment]
You can send sensitive information to shaka-player-issues@google.com.  Thank you!

**Comment by haby0** [comment]
I sent the details of the vulnerability to the email address you gave me. But no feedback.

**Comment by joeyparrish** [comment]
We apologize for the delay.  Thank you for your report, and your offer of a PR to fix it.  A PR would be very welcome!

**Comment by haby0** [comment]
@joeyparrish Please check PR.

**Comment by haby0** [comment]
@joeyparrish Hi, can you disclose this vulnerability and apply for a CVE?

Reference: https://docs.github.com/en/code-security/security-advisories/creating-a-security-advisory
