### ISSUE TITLE
[Q] Adaptive resolution

### ISSUE THREAD

**Issue by Angels-group** [google/shaka-streamer#24]
First of all - many thanks for this project! I have been waiting for him for a very long time) Well done!

I did not understand a little about the mechanism of work.
If I have the source (h264, mp4) with one video track - 1080p, then on the output, after shaka-streamer works, can I have only one video track? I can’t encode in 1080p and 720p on the fly so that I can select the video track in the player on the client side?

**Comment by ismena** [comment]
Hi @Angels-group 

You can configure the kind of output you want for your source track.
Is it VOD? Take a look at our [sample configs](https://github.com/google/shaka-streamer/tree/master/config_files) ([here's the one for VOD](https://github.com/google/shaka-streamer/blob/master/config_files/pipeline_vod_config.yaml)). Under "resolutions" you would list the resolutions you want for your output.
If you list both 1080p and 720p, you will get tracks in both as a result:
`transcoder:
  resolutions:
    - 1080p
    - 720p`

If you add more resolutions (like 360p, 480p...), you will get tracks in those too! :)

Does it help?
@joeyparrish Do we have config file usage FAQ/tutorials anywhere? If not, it might be a good idea to write some.

**Comment by Angels-group** [comment]
Hi @ismena !

Thanks for the answer! Yes, VOD.

> You can configure the kind of output you want for your source track.
> 
> If you list both 1080p and 720p, you will get tracks in both as a result:
> `transcoder: resolutions: - 1080p - 720p`
> 
> If you add more resolutions (like 360p, 480p...), you will get tracks in those too! :)

I understood this part) I wanted to clarify the moment with the source.
There is only one video track in the source: 1080p resolution

Can I specify in the configuration (.yaml) the rest of the tracks (for example 720p, 360p etc) or only those that are in the source file (1080p) ?

**Comment by ismena** [comment]
Oh, sorry. Let's make sure I understand the question correctly before I give you more random unhelpful info :)

What do you mean by "the rest of the tracks?" Are those the tracks that exist for the source, but you're not giving them to the pipeline? Are those the resulting resolutions you want to get out of the streamer?

You have a video stream of 1080p, correct? What do you want to have by the time the streamer stops working?

**Comment by Angels-group** [comment]
This is all my not very good English to blame :) Sorry)

I have a source video.mp4 (h264) file with one video track - 1080p

Can I use Shaka Streamer to get a stream with different tracks (1080p, 720p, 480p, 360p) on the output of DASH (or HLS) from this file?

**Comment by ismena** [comment]
Ah, gotcha! Your English is fine, but I actually also speak Russian, if everything else fails :)

Yes, you can totally use the Streamer to get all those tracks. The only thing that won't work is if you want to go up (like if you have a 1080p stream, we can't make a 4k stream out of it).

We have 2 configs: one for the input, one for the pipeline. The [input config](https://github.com/google/shaka-streamer/blob/master/config_files/input_vod_config.yaml) is where all the info about your source goes (so, you will put '1080p' under 'resolution').
The [pipeline config](https://github.com/google/shaka-streamer/blob/master/config_files/pipeline_vod_config.yaml) is about the output, so you will list there all the resolutions you want to get from the pipeline when it's done. (1080p, 720p, etc)

Does it make sense?

**Comment by Angels-group** [comment]
> I actually also speak Russian, if everything else fails :)
and it is wonderful! I am very pleased to hear that)

> Does it make sense?
Excellent! This is what I wanted to hear)
And it is very pleasing. Shaka Streamer - what I was waiting for)
Thank you so much!!!

Is there such a possibility with liveStream (instead of VOD)?

**Comment by joeyparrish** [comment]
Yes, Shaka Streamer supports both live and VOD.  See the `streaming_mode` field in the pipeline config, and the examples in `config_files/` with "live" or "vod" in the name.

We will have full documentation coming very soon (in review now) to be served on GitHub pages.

**Comment by joeyparrish** [comment]
You can also push your live stream directly to Google Cloud Storage or Amazon S3 with the `-c` argument.  Try running with `--help` to see a description of that option, if you're interested.

**Comment by Angels-group** [comment]
@joeyparrish 
I managed to run shaka-streamer on mac os. I tried both live and VOD.

Got a question:
Playlist manifest (hls or dash) is generated only after transcoding the entire file duration.
Thus, I can connect to the stream only after full transcoding. So it should be?
I can’t connect to Live or VOD stream during encoding to watch segments that are already ready?

**Comment by joeyparrish** [comment]
@Angels-group, have we answered your question?  Is there anything else we can do for you on this issue, or may we close it?

**Comment by Angels-group** [comment]
@joeyparrish @ismena 
Yes, you can close it. I got an answer to my question. I even tested and made sure that everything works as it should! Thank you so much !

**Comment by joeyparrish** [comment]
Always happy to help!
