### ISSUE TITLE
Add support to multiple channel output options

### ISSUE THREAD

**Issue by avelad** [google/shaka-streamer#38]
I want to be able to generate an output with audio 2.0 and 5.1.

Now, only one channel configuration is supported.

**Comment by joeyparrish** [comment]
To clarify, do you want to have one 2-channel input and one 6-channel input and have those turn into 2-channel and 6-channel output, respectively?  Or do you want one 6-channel input turned into both a 6-channel input and a 2-channel output (downmixed)?

**Comment by avelad** [comment]
I want the second option. 

ej:
input
- AC3 6 channels

output
- AC3 6 channels
- AC3 2 channels (downmixed)
- AAC 6 channels
- AAC 2 channels (downmixed)

Note: It would also be nice to be able to select the bitrate of the audio. Eg: AAC 96kbps and AAC 128kbps

**Comment by joeyparrish** [comment]
You can already change the output bitrates and redefine the resolutions with today's `master` branch, and in the upcoming v0.3.0 release.  It's done through an additional config file.  See [`config_files/bitrate_config.yaml`](https://github.com/google/shaka-streamer/blob/master/config_files/bitrate_config.yaml) and the `-b` option on the command-line.

The downmixing of input to various output channels isn't supported yet, but I'll add this as an enhancement for v1.0.

**Comment by avelad** [comment]
Yes it is true that this configuration exists, but I think that in my previous comment I was not clear.

I wish I could configure this:
- AAC 2 channels at 96kpbs
- AAC 2 channels at 128kbps

In the configuration example, it is only possible to establish an stereo configuration, or at least I understood that. I need 2 configurations for stereo

**Comment by joeyparrish** [comment]
Ah, I see.  Let's make that a separate feature request.
