### ISSUE TITLE
DRM protected streams

### ISSUE THREAD

**Issue by furkyto** [google/shaka-streamer#39]
Any help with drm protected streams ?

**Comment by joeyparrish** [comment]
Yes, we support Widevine DRM.  We also have an open feature request to support Shaka Packager's raw key support with a custom PSSH (#21).

In the pipeline config, you can enable encryption with:

```yaml
encryption:
  enable: true
```

The full docs for the encryption section can be found here: https://google.github.io/shaka-streamer/configuration_fields.html#streamer.pipeline_configuration.EncryptionConfig

In this section, you can choose your content ID (default random), license server (default UAT), and credentials (default "widevine_test"), as well as encryption scheme (default "cenc") and clear lead (default 10 seconds).

If there are other DRM-related features you are interested in, please let us know!

Does this answer your question?

**Comment by furkyto** [comment]
i want to ask you in private some questions , could you please give me email or skype ?

**Comment by joeyparrish** [comment]
Sorry, it's very difficult to provide one-on-one assistance via email, and the community in general may benefit from seeing the answers to your questions.  If you have a problem, someone else may have the same or similar problem.

If your question is about Shaka Streamer configuration for DRM, so long as you avoid providing your Widevine credentials on GitHub, you should be able to safely share other details.

If your question is about Widevine features or other Widevine-specific questions, your best option is to contact Widevine for support.  Widevine support tickets are completely private.  https://www.widevine.com/contact
