### ISSUE TITLE
How to config the input file not transcode just packager?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/shaka-streamer#40]
Use case: 
 To input a stream with 1080p,  want to output 3 HLS streams with 1080p, 720p, 640p, so the output 1080p stream just need to package, other two stream need to transcode and package. How to config?

**Comment by joeyparrish** [comment]
Sorry, that's not supported.  As you've discovered recently in https://github.com/google/shaka-packager/issues/665#issuecomment-544135951, there may be compatibility issues with the original encoding.

**Comment by joeyparrish** [comment]
Also, if you want to package only, you could always use Shaka Packager directly.

Thanks for your feedback!
