### ISSUE TITLE
New To CMAF...Any Demo Source Code?

### ISSUE THREAD

**Issue by rayj00** [google/shaka-streamer#48]
Not really and issue but a general question.  I am researching CMAF for live streaming.  Is there any demo code available?  I am not sure how I would access my web cam and then use CMAF for distribution.

Thanks,

Ray

**Comment by joeyparrish** [comment]
CMAF (Common Media Application Format) just means streaming with fragmented MP4/ISOBMFF, which isn't new or difficult or interesting.  By default, Shaka Streamer will encode content in fragmented MP4.

For an example, see these config files:
 - https://github.com/google/shaka-streamer/blob/master/config_files/input_webcam_config.yaml
 - https://github.com/google/shaka-streamer/blob/master/config_files/pipeline_live_config.yaml

Does this help?
