### ISSUE TITLE
Downmix 8 independent audio streams

### ISSUE THREAD

**Issue by JSONPARS** [google/shaka-streamer#52]
Hi!
I'm trying to transcode an packetize an mxf file with shaka-streamer. Unfortunately I keep getting the error:
`[Parsed_channelmap_0 @ 0x55e2b01831c0] input channel #1 not available from input layout 'mono'
[Parsed_channelmap_0 @ 0x55e2b01831c0] input channel #2 not available from input layout 'mono'
[Parsed_channelmap_0 @ 0x55e2b01831c0] input channel #3 not available from input layout 'mono'
[Parsed_channelmap_0 @ 0x55e2b01831c0] input channel #4 not available from input layout 'mono'
[Parsed_channelmap_0 @ 0x55e2b01831c0] input channel #5 not available from input layout 'mono'
[Parsed_channelmap_0 @ 0x55e2b01831c0] Failed to configure input pad on Parsed_channelmap_0
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:1`
My mxf file has 8 audio streams, which have to be mixed to a stereo track when transcoding.
How is the syntax in shaka-streamer for this? I will add the link to the mxf file later, because the upload still takes a while...

**Comment by joeyparrish** [comment]
Can you give us the full output of Shaka Streamer?  In that will be ffmpeg commands generated by Streamer, which may help us understand the issue.

Having access to the content would also help a lot.  You can share content privately by email to shaka-player-issues@google.com.  Thanks!

**Comment by JSONPARS** [comment]
Sure, here comes the full output:
`shaka-streamer -i input_vod_config.yaml -p pipeline_vod_config.yaml -o Output
+ ffprobe G75278_MeinNachmittag_Beitrag.mxf -select_streams v:0 -show_entries stream=field_order -of compact=p=0:nk=1
+ ffprobe G75278_MeinNachmittag_Beitrag.mxf -select_streams v:0 -show_entries stream=r_frame_rate -of compact=p=0:nk=1
+ ffprobe G75278_MeinNachmittag_Beitrag.mxf -select_streams v:0 -show_entries stream=width,height -of compact=p=0:nk=1
+ ffprobe G75278_MeinNachmittag_Beitrag.mxf -select_streams a:0 -show_entries stream_tags=language -of compact=p=0:nk=1
+ ffmpeg -y -i G75278_MeinNachmittag_Beitrag.mxf -i G75278_MeinNachmittag_Beitrag.mxf -map 0:v:0 -r 12.5 -preset slow -flags +loop -f mpegts -pix_fmt yuv420p -flags +cgop -profile:v high -an -c:v h264 -b:v 4M -keyint_min 75 -g 75 -vf pp=fd,scale=-2:1080,setsar=1:1 /tmp/shaka-live-gsrb1x2i/bbff9cfd-42eb-490b-88a8-298b27536b92 -map 0:v:0 -r 12.5 -preset slow -flags +loop -f mpegts -pix_fmt yuv420p -flags +cgop -profile:v high -an -c:v h264 -b:v 2M -keyint_min 75 -g 75 -vf pp=fd,scale=-2:720,setsar=1:1 /tmp/shaka-live-gsrb1x2i/a2b254d6-9eef-466d-ac50-91581d2d9a68 -map 0:v:0 -r 12.5 -preset slow -flags +loop -f mpegts -pix_fmt yuv420p -flags +cgop -profile:v main -an -c:v h264 -b:v 1M -keyint_min 75 -g 75 -vf pp=fd,scale=-2:480,setsar=1:1 /tmp/shaka-live-gsrb1x2i/cc0ff5b6-5925-40f2-9050-943309997b9d -map 0:v:0 -r 12.5 -preset slow -flags +loop -f mpegts -pix_fmt yuv420p -flags +cgop -profile:v main -an -c:v h264 -b:v 400k -keyint_min 75 -g 75 -vf pp=fd,scale=-2:360,setsar=1:1 /tmp/shaka-live-gsrb1x2i/e0adf83e-ba60-4fc4-a0ae-6dcb075eeb41 -map 1:a:0 -vn -ac 6 -c:a aac -b:a 192k -f mpegts -af channelmap=channel_layout=5.1 /tmp/shaka-live-gsrb1x2i/b3932154-cf6d-47bc-a286-e9842aedca30
+ packager 'in=/tmp/shaka-live-gsrb1x2i/bbff9cfd-42eb-490b-88a8-298b27536b92,stream=video,init_segment=Output//video_1080p_4M_init.mp4,segment_template=Output//video_1080p_4M_$Number$.mp4' 'in=/tmp/shaka-live-gsrb1x2i/a2b254d6-9eef-466d-ac50-91581d2d9a68,stream=video,init_segment=Output//video_720p_2M_init.mp4,segment_template=Output//video_720p_2M_$Number$.mp4' 'in=/tmp/shaka-live-gsrb1x2i/cc0ff5b6-5925-40f2-9050-943309997b9d,stream=video,init_segment=Output//video_480p_1M_init.mp4,segment_template=Output//video_480p_1M_$Number$.mp4' 'in=/tmp/shaka-live-gsrb1x2i/e0adf83e-ba60-4fc4-a0ae-6dcb075eeb41,stream=video,init_segment=Output//video_360p_400k_init.mp4,segment_template=Output//video_360p_400k_$Number$.mp4' 'in=/tmp/shaka-live-gsrb1x2i/b3932154-cf6d-47bc-a286-e9842aedca30,stream=audio,init_segment=Output//audio_und_6c_192k_init.mp4,segment_template=Output//audio_und_6c_192k_$Number$.mp4' --segment_duration 6 --generate_static_mpd --mpd_output Output/dash.mpd --hls_playlist_type VOD --hls_master_playlist_output Output/hls.m3u8
ffmpeg version N-94739-ge0fab59624 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --enable-libvmaf --enable-version3 --enable-gpl --enable-nonfree --enable-libx264 --enable-libx265 --enable-libvpx --enable-libfdk-aac --enable-libaom --enable-libfreetype --enable-libfontconfig --enable-libopus
  libavutil      56. 34.100 / 56. 34.100
  libavcodec     58. 56.101 / 58. 56.101
  libavformat    58. 31.104 / 58. 31.104
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 58.102 /  7. 58.102
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
WARNING: generate_static_mpd is deprecated and ignored. Please switch to --generate_static_live_mpd.
WARNING: generate_static_mpd is deprecated and ignored. Please switch to --generate_static_live_mpd.
[0304/163731:INFO:demuxer.cc(88)] Demuxer::Run() on file '/tmp/shaka-live-gsrb1x2i/a2b254d6-9eef-466d-ac50-91581d2d9a68'.
[0304/163731:INFO:demuxer.cc(160)] Initialize Demuxer for file '/tmp/shaka-live-gsrb1x2i/a2b254d6-9eef-466d-ac50-91581d2d9a68'.
[0304/163731:INFO:demuxer.cc(88)] Demuxer::Run() on file '/tmp/shaka-live-gsrb1x2i/b3932154-cf6d-47bc-a286-e9842aedca30'.
[0304/163731:INFO:demuxer.cc(160)] Initialize Demuxer for file '/tmp/shaka-live-gsrb1x2i/b3932154-cf6d-47bc-a286-e9842aedca30'.
[0304/163731:INFO:demuxer.cc(88)] Demuxer::Run() on file '/tmp/shaka-live-gsrb1x2i/bbff9cfd-42eb-490b-88a8-298b27536b92'.
[0304/163731:INFO:demuxer.cc(160)] Initialize Demuxer for file '/tmp/shaka-live-gsrb1x2i/bbff9cfd-42eb-490b-88a8-298b27536b92'.
[0304/163731:INFO:demuxer.cc(88)] Demuxer::Run() on file '/tmp/shaka-live-gsrb1x2i/cc0ff5b6-5925-40f2-9050-943309997b9d'.
[0304/163731:INFO:demuxer.cc(160)] Initialize Demuxer for file '/tmp/shaka-live-gsrb1x2i/cc0ff5b6-5925-40f2-9050-943309997b9d'.
[0304/163731:INFO:demuxer.cc(88)] Demuxer::Run() on file '/tmp/shaka-live-gsrb1x2i/e0adf83e-ba60-4fc4-a0ae-6dcb075eeb41'.
[0304/163731:INFO:demuxer.cc(160)] Initialize Demuxer for file '/tmp/shaka-live-gsrb1x2i/e0adf83e-ba60-4fc4-a0ae-6dcb075eeb41'.
Guessed Channel Layout for Input Stream #0.1 : mono
Guessed Channel Layout for Input Stream #0.2 : mono
Guessed Channel Layout for Input Stream #0.3 : mono
Guessed Channel Layout for Input Stream #0.4 : mono
Guessed Channel Layout for Input Stream #0.5 : mono
Guessed Channel Layout for Input Stream #0.6 : mono
Guessed Channel Layout for Input Stream #0.7 : mono
Guessed Channel Layout for Input Stream #0.8 : mono
Input #0, mxf, from 'G75278_MeinNachmittag_Beitrag.mxf':
  Metadata:
    operational_pattern_ul: 060e2b34.04010101.0d010201.01010900
    uid             : ea29e8c1-c9a6-11e9-b1c9-b499bac1bc64
    generation_uid  : ea29e8c2-c9a6-11e9-9fff-b499bac1bc64
    company_name    : Telestream
    product_name    : Flip Technology
    product_version : 3.0
    application_platform: win32
    product_uid     : ffeeddcc-bbaa-9988-7766-554433221100
    modification_date: 2019-08-28T15:17:14.072000Z
    material_package_umid: 0x060A2B340101010501010D1213000000EE414803238705A57657B499BAC1BC64
    timecode        : 10:00:00:00
  Duration: 00:08:25.40, start: 0.000000, bitrate: 57128 kb/s
    Stream #0:0: Video: mpeg2video (4:2:2), yuv422p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 50000 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 1
    Stream #0:1: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 2
    Stream #0:2: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 3
    Stream #0:3: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 4
    Stream #0:4: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 5
    Stream #0:5: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 6
    Stream #0:6: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 7
    Stream #0:7: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 8
    Stream #0:8: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 9
    Stream #0:9: Data: none
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 10
      data_type       : vbi_vanc_smpte_436M
Guessed Channel Layout for Input Stream #1.1 : mono
Guessed Channel Layout for Input Stream #1.2 : mono
Guessed Channel Layout for Input Stream #1.3 : mono
Guessed Channel Layout for Input Stream #1.4 : mono
Guessed Channel Layout for Input Stream #1.5 : mono
Guessed Channel Layout for Input Stream #1.6 : mono
Guessed Channel Layout for Input Stream #1.7 : mono
Guessed Channel Layout for Input Stream #1.8 : mono
Input #1, mxf, from 'G75278_MeinNachmittag_Beitrag.mxf':
  Metadata:
    operational_pattern_ul: 060e2b34.04010101.0d010201.01010900
    uid             : ea29e8c1-c9a6-11e9-b1c9-b499bac1bc64
    generation_uid  : ea29e8c2-c9a6-11e9-9fff-b499bac1bc64
    company_name    : Telestream
    product_name    : Flip Technology
    product_version : 3.0
    application_platform: win32
    product_uid     : ffeeddcc-bbaa-9988-7766-554433221100
    modification_date: 2019-08-28T15:17:14.072000Z
    material_package_umid: 0x060A2B340101010501010D1213000000EE414803238705A57657B499BAC1BC64
    timecode        : 10:00:00:00
  Duration: 00:08:25.40, start: 0.000000, bitrate: 57128 kb/s
    Stream #1:0: Video: mpeg2video (4:2:2), yuv422p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 50000 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 1
    Stream #1:1: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 2
    Stream #1:2: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 3
    Stream #1:3: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 4
    Stream #1:4: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 5
    Stream #1:5: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 6
    Stream #1:6: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 7
    Stream #1:7: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 8
    Stream #1:8: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 9
    Stream #1:9: Data: none
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 10
      data_type       : vbi_vanc_smpte_436M
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video (native) -> h264 (libx264))
  Stream #0:0 -> #1:0 (mpeg2video (native) -> h264 (libx264))
  Stream #0:0 -> #2:0 (mpeg2video (native) -> h264 (libx264))
  Stream #0:0 -> #3:0 (mpeg2video (native) -> h264 (libx264))
  Stream #1:1 -> #4:0 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x555872cd6600] using SAR=1/1
[libx264 @ 0x555872cd6600] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 0x555872cd6600] profile High, level 5.0, 4:2:0, 8-bit
Output #0, mpegts, to '/tmp/shaka-live-gsrb1x2i/bbff9cfd-42eb-490b-88a8-298b27536b92':
  Metadata:
    operational_pattern_ul: 060e2b34.04010101.0d010201.01010900
    uid             : ea29e8c1-c9a6-11e9-b1c9-b499bac1bc64
    generation_uid  : ea29e8c2-c9a6-11e9-9fff-b499bac1bc64
    company_name    : Telestream
    product_name    : Flip Technology
    product_version : 3.0
    application_platform: win32
    product_uid     : ffeeddcc-bbaa-9988-7766-554433221100
    modification_date: 2019-08-28T15:17:14.072000Z
    material_package_umid: 0x060A2B340101010501010D1213000000EE414803238705A57657B499BAC1BC64
    timecode        : 10:00:00:00
    encoder         : Lavf58.31.104
    Stream #0:0: Video: h264 (libx264), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 4000 kb/s, 12.50 fps, 90k tbn, 12.50 tbc
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 1
      encoder         : Lavc58.56.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/4000000 buffer size: 0 vbv_delay: N/A
[libx264 @ 0x555872cd8ec0] using SAR=1/1
[libx264 @ 0x555872cd8ec0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 0x555872cd8ec0] profile High, level 3.1, 4:2:0, 8-bit
Output #1, mpegts, to '/tmp/shaka-live-gsrb1x2i/a2b254d6-9eef-466d-ac50-91581d2d9a68':
  Metadata:
    operational_pattern_ul: 060e2b34.04010101.0d010201.01010900
    uid             : ea29e8c1-c9a6-11e9-b1c9-b499bac1bc64
    generation_uid  : ea29e8c2-c9a6-11e9-9fff-b499bac1bc64
    company_name    : Telestream
    product_name    : Flip Technology
    product_version : 3.0
    application_platform: win32
    product_uid     : ffeeddcc-bbaa-9988-7766-554433221100
    modification_date: 2019-08-28T15:17:14.072000Z
    material_package_umid: 0x060A2B340101010501010D1213000000EE414803238705A57657B499BAC1BC64
    timecode        : 10:00:00:00
    encoder         : Lavf58.31.104
    Stream #1:0: Video: h264 (libx264), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=-1--1, 2000 kb/s, 12.50 fps, 90k tbn, 12.50 tbc
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 1
      encoder         : Lavc58.56.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/2000000 buffer size: 0 vbv_delay: N/A
[libx264 @ 0x555872d2fb80] using SAR=1/1
[libx264 @ 0x555872d2fb80] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 0x555872d2fb80] profile Main, level 2.2, 4:2:0, 8-bit
Output #2, mpegts, to '/tmp/shaka-live-gsrb1x2i/cc0ff5b6-5925-40f2-9050-943309997b9d':
  Metadata:
    operational_pattern_ul: 060e2b34.04010101.0d010201.01010900
    uid             : ea29e8c1-c9a6-11e9-b1c9-b499bac1bc64
    generation_uid  : ea29e8c2-c9a6-11e9-9fff-b499bac1bc64
    company_name    : Telestream
    product_name    : Flip Technology
    product_version : 3.0
    application_platform: win32
    product_uid     : ffeeddcc-bbaa-9988-7766-554433221100
    modification_date: 2019-08-28T15:17:14.072000Z
    material_package_umid: 0x060A2B340101010501010D1213000000EE414803238705A57657B499BAC1BC64
    timecode        : 10:00:00:00
    encoder         : Lavf58.31.104
    Stream #2:0: Video: h264 (libx264), yuv420p, 854x480 [SAR 1:1 DAR 427:240], q=-1--1, 1000 kb/s, 12.50 fps, 90k tbn, 12.50 tbc
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 1
      encoder         : Lavc58.56.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/1000000 buffer size: 0 vbv_delay: N/A
[libx264 @ 0x555872cd4640] using SAR=1/1
[libx264 @ 0x555872cd4640] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 0x555872cd4640] profile Main, level 2.2, 4:2:0, 8-bit
Output #3, mpegts, to '/tmp/shaka-live-gsrb1x2i/e0adf83e-ba60-4fc4-a0ae-6dcb075eeb41':
  Metadata:
    operational_pattern_ul: 060e2b34.04010101.0d010201.01010900
    uid             : ea29e8c1-c9a6-11e9-b1c9-b499bac1bc64
    generation_uid  : ea29e8c2-c9a6-11e9-9fff-b499bac1bc64
    company_name    : Telestream
    product_name    : Flip Technology
    product_version : 3.0
    application_platform: win32
    product_uid     : ffeeddcc-bbaa-9988-7766-554433221100
    modification_date: 2019-08-28T15:17:14.072000Z
    material_package_umid: 0x060A2B340101010501010D1213000000EE414803238705A57657B499BAC1BC64
    timecode        : 10:00:00:00
    encoder         : Lavf58.31.104
    Stream #3:0: Video: h264 (libx264), yuv420p, 640x360 [SAR 1:1 DAR 16:9], q=-1--1, 400 kb/s, 12.50 fps, 90k tbn, 12.50 tbc
    Metadata:
      file_package_umid: 0x060A2B340101010501010D12131B8923C5414803238705A56E44B499BAC1BC64
      file_package_name: Source Package
      track_name      : Track 1
      encoder         : Lavc58.56.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/400000 buffer size: 0 vbv_delay: N/A
[Parsed_channelmap_0 @ 0x555873c568c0] input channel #1 not available from input layout 'mono'
[Parsed_channelmap_0 @ 0x555873c568c0] input channel #2 not available from input layout 'mono'
[Parsed_channelmap_0 @ 0x555873c568c0] input channel #3 not available from input layout 'mono'
[Parsed_channelmap_0 @ 0x555873c568c0] input channel #4 not available from input layout 'mono'
[Parsed_channelmap_0 @ 0x555873c568c0] input channel #5 not available from input layout 'mono'
[Parsed_channelmap_0 @ 0x555873c568c0] Failed to configure input pad on Parsed_channelmap_0
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:1
[0304/163731:ERROR:demuxer.cc(204)] Failed to detect the container type from the buffer: 
[0304/163731:ERROR:demuxer.cc(204)] Failed to detect the container type from the buffer: 
[0304/163731:ERROR:demuxer.cc(204)] Failed to detect the container type from the buffer: 
[0304/163731:ERROR:demuxer.cc(204)] Failed to detect the container type from the buffer: 
[0304/163731:ERROR:demuxer.cc(204)] Failed to detect the container type from the buffer: 
[0304/163731:ERROR:packager_main.cc(533)] Packaging Error: 3 (INVALID_ARGUMENT): Failed to detect the container type.
[libx264 @ 0x555872cd6600] final ratefactor: 13.90
[libx264 @ 0x555872cd8ec0] final ratefactor: 16.36
[libx264 @ 0x555872d2fb80] final ratefactor: 18.90
[libx264 @ 0x555872cd4640] final ratefactor: 24.39
Conversion failed!
`
The email with the original content is on its way.

**Comment by joeyparrish** [comment]
It looks like 8 independent mono audio streams.  We never considered this as a use-case.

My advice would be to mix the audio together yourself ahead of time, since this is VOD.  Would that be too complicated?

**Comment by jimmyspets** [comment]
Did you find a sollution?
I have a simmilar case where I have a prores file from a Black Magic Design recorder where the 16 audio channels from the SDI are recorded as a 16 channel mono track. I have four steropairs that I use on channel 1-2, 3-4, 5-6 an 7-8 and would like to use the shaka-streamer to encode this to hls/dash.

**Comment by joeyparrish** [comment]
My advice would be to mix the audio together yourself ahead of time, since this is VOD. Would that be too complicated?
