### ISSUE TITLE
Docs fix

### ISSUE THREAD

**Issue by solaris7x** [google/shaka-streamer#56]
While following the shaka-streamer docs , There is a typo under Installing Prerequisites / [Test Dependencies (optional)](https://github.com/google/shaka-streamer/blob/master/docs/source/prerequisites.rst#test-dependencies-optional) `sudo apt -y python3-flask nodejs npm`  , as it needs to be `sudo apt install -y python3-flask nodejs npm` 

Also I'm using Ubuntu 18.04 LTS and wasnt able to install libnvidia-encode1 , no such package was found but I already had package cuda and nvidia drivers installed thus I have shaka-streamer working with hwaccel

**Comment by joeyparrish** [comment]
Thanks for pointing this out!  It should be fixed now.
