### ISSUE TITLE
Can't play hls VOD on android browser

### ISSUE THREAD

**Issue by abhiwagh** [google/shaka-streamer#57]
I have encoded video using input_vod_config.yaml and pipeline_vod_config.yaml (attached here)using shaka-streamer.

The video is working properly in shaka player / other hls players but not working in google chrome in my android phone.

Can you help me in this regard.
[configs.zip](https://github.com/google/shaka-streamer/files/4700893/configs.zip)

**Comment by joeyparrish** [comment]
What error or other behavior do you get when you try to play HLS directly in the browser on Android?

**Comment by abhiwagh** [comment]
I checked the console of browser but cant find any error logged.

Also in network tab of dev console of chrome master manifest downloaded successfully.

**Comment by solaris7x** [comment]
This may be the issue of unsupported codec , please check your console for Warnings too 
If possible please add or change the codecs accordingly and try to play again 
![image](https://user-images.githubusercontent.com/21334098/83483198-be802780-a4bf-11ea-81c4-2fd3db317818.png)
