### ISSUE TITLE
Is raw key encryption now supported with shaka-streamer?

### ISSUE THREAD

**Issue by ctoshni** [google/shaka-streamer#59]
Can we provide raw key for encryption  with shaka-streamer?

Also, how can I see all the commands generated by shaka-streamer?

**Comment by joeyparrish** [comment]
The commands generated by Shaka Streamer are shown in the console output, prefixed by `+` as you would see from a bash script using `set -x`.

Raw key encryption is not yet supported.  Please see https://github.com/google/shaka-streamer/issues/21

Does this answer your questions?
