### ISSUE TITLE
Final mpd, m3u8 files are not getting uploaded to s3

### ISSUE THREAD

**Issue by Karthik-0** [google/shaka-streamer#67]
Once transcoding is completed, mpd and m3u8 was not uploaded to s3. Instead, I am getting the following error.
```python
XML API does not suport gzip-encoded uploads.
XML API does not suport gzip-encoded uploads.
XML API does not suport gzip-encoded uploads.
XML API does not suport gzip-encoded uploads.
CommandException: 4 files/objects could not be copied/removed.
Exception ignored in: <function NodeBase.__del__ at 0x7ff5153b9440>
Traceback (most recent call last):
  File "/Users/karthik/.virtualenvs/shaka-streamer/lib/python3.7/site-packages/streamer/node_base.py", line 51, in __del__
  File "/Users/karthik/.virtualenvs/shaka-streamer/lib/python3.7/site-packages/streamer/cloud_node.py", line 166, in stop
  File "/Users/karthik/.virtualenvs/shaka-streamer/lib/python3.7/site-packages/streamer/cloud_node.py", line 155, in _thread_single_pass
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
subprocess.CalledProcessError: Command '['gsutil', '-q', '-h', 'Cache-Control: no-store, no-transform', '-m', 'rsync', '-C', '-r', '-J', '/var/folders/_n/yh4n50b56mbfcylxthnvhqxc0000gq/T/shaka-live-_38aidcf/cloud', 's3://bucket_url/shaka_streamer/streamer/test_upload']' returned non-zero exit status 1.
```

When I checked further, I found [gsutil](https://github.com/GoogleCloudPlatform/gsutil/blob/8279ce95f35e36fd0f87fb8f2802ce70d135f2c0/gslib/boto_translation.py#L1048) raises this error when `-J` arg is provided.

**Comment by joeyparrish** [comment]
We have a plan to get rid of the gsutil-based cloud upload in favor of Shaka Packager's HTTP output support.  To make this work well, we will need to set up local authentication proxies for GCS and S3 to refresh and add auth tokens to the requests.  (I just realized I need to file an issue for that.)

In the meantime, we can skip -J for s3:// URLs.  It seems to still work for GCS.

**Comment by joeyparrish** [comment]
(Tracking CloudNode deprecation now in #47)
