### ISSUE TITLE
Unable to use shaka streamer

### ISSUE THREAD

**Issue by upanitag** [google/shaka-streamer#98]
I get the following error when running shaka streamer

Fatal error:
  Shaka Packager not found! Please install version 2.5.1 or higher of Shaka Packager.

I used the following commands in my debian machine
sudo pip3 install --upgrade shaka-streamer shaka-streamer-binaries

I also updated LD_LIBRARY_PATH and PATH variable to the location of the shaka-streamer-binaries.

$ python3 shaka-streamer  -i /usr/local/bin/input_looped_file_config.yaml -p /usr/local/bin/pipeline_live_config.yaml -o /home/ugoswami/foo.mpd
Fatal error:
  Shaka Packager not found! Please install version 2.5.1 or higher of Shaka Packager.

$ ls -ltr
total 48060
-rwxr-xr-x+ 1 ugoswami users 42725832 Oct  1 14:50 ffmpeg-linux-x64*
-rwxr-xr-x+ 1 ugoswami users 42619496 Oct  1 14:50 ffprobe-linux-x64*
-rwxr-xr-x+ 1 ugoswami users  6887056 Oct  1 14:50 packager-linux-x64*
-rwxr-xr-x+ 1 ugoswami users     4571 Oct  1 14:51 shaka-streamer*

What am I missing?

**Comment by joeyparrish** [comment]
What OS are you using?

What is the path you added to PATH for the binaries?  (You shouldn't have to add anything to PATH, by the way, but I'd like to explore it since I don't know what the problem is yet.)

**Comment by upanitag** [comment]
I am on Debian 10. 
export PATH:$PATH:<Location to packager-linux-x64>

Initially I had the shaka-streamer and packager-linux-x64 in two different locations. Later I put everything on the same directory. But it still did not work. That makes me think it is not a path issue. A verbose flag when running shaka-streamer will be nice.

**Comment by meryacine** [comment]
@joeyparrish I believe the version on PyPi right now doesn't have the `streamer_binaries` integration yet.

**Comment by joeyparrish** [comment]
@meryacine, I just noticed that myself.  v2.5.1 was the minimum version required _before_ we introduced the `shaka-streamer-binaries` package.

Looking more closely, we never completed the v0.5.0 release of Streamer!  @upanitag, we apologize for the inconvenience.

@meryacine, do you know any reason I shouldn't push out Streamer v0.5.0 right now?

**Comment by meryacine** [comment]
@joeyparrish Nothing, I think it is ready for v0.5.0 .

**Comment by joeyparrish** [comment]
Great, I'll push that out today.  @upanitag, we should have it fixed shortly with the new release.  Sorry for the trouble!

**Comment by upanitag** [comment]
Thank you !

**Comment by joeyparrish** [comment]
Shaka Streamer v0.5.0 is [tagged on GitHub](https://github.com/google/shaka-streamer/releases/tag/v0.5.0) and [pushed to PyPi](https://pypi.org/project/shaka-streamer/0.5.0/).  Everything should work with the binaries package now.

You should not need to copy the binaries anywhere, or add anything to your PATH.  The `shaka-streamer` command will load the binaries package to get the exact paths to those binaries.

Please let us know if this has fixed the issue for you.

**Comment by upanitag** [comment]
Thanks. The error went away. I do get a different error. Opening a new ticket https://github.com/google/shaka-streamer/issues/99
